services:
  tr-watcher:
    image: openmpy/tr-watcher:latest
    container_name: tr-watcher
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data:/app/data
      - type: bind
        source: .env
        target: /app/.env

volumes:
  data:
